### ISSUE TITLE
Go to a specific date

### ISSUE THREAD

**Issue by dscravag** [QwantResearch/qwant-cozy-webextension#24]
If not ready for this first release, "Go to a specific date" should be hidden

**Comment by kamilzola** [comment]
It might look like it's not working when there are no results for given day, so message will show with number of results when day filtering is active (as in search/filtering with phrase). I'll close it when changes get integrated with main branch - let me know if problem is of another nature.

**Comment by dscravag** [comment]
As for Hugo's design, an icon should be shown which will show a date picker.
https://app.zeplin.io/project/5ae2eaa7a6519b3681df5d41/screen/5aec823a35ab301d29b9ee7b

If there are no data for a specific date, it should show the "EMPTY DAY" message
https://app.zeplin.io/project/5ae2eaa7a6519b3681df5d41/screen/5b39e0a82496b56225acdc6a

**Comment by kamilzola** [comment]
The message will be there when day without content is selected, but I don't think it make sense to show it when there are multiple days shown (as shown in picture), because it can lead to situation where tens or hundreds of consecutive days are displayed with this message.
